SELECT * FROM Orders WHERE Freight BETWEEN 25 AND 30 ORDER BY Freight, ShipVia
SELECT * FROM Orders WHERE Freight BETWEEN 25 AND 30 ORDER BY Freight DESC
SELECT CustomerID ,EmployeeID, Freight*100 Height FROM Orders ORDER BY HEIGHT
SELECT * FROM ORDERS WHERE EmployeeID IN (5,6) AND ShipName LIKE 'W%' -- STARTS WITH 'W' CHARACTER
SELECT * FROM ORDERS WHERE EmployeeID NOT IN (5,6) AND ShipName LIKE '%SAVE%' -- CONTAINS SUBSTRING 'SAVE'